//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Repository.Repositories.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_account
    {
        public long bank_account_id { get; set; }
        public string number { get; set; }
        public decimal balance { get; set; }
        public bool locked { get; set; }
        public Nullable<long> customer_id { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
