//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Repository.Repositories.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Bank_account = new HashSet<Bank_account>();
        }
    
        public long customer_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
    
        public virtual ICollection<Bank_account> Bank_account { get; set; }
    }
}
